# Generated by Django 4.2 on 2025-11-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=60)),
                ('director_name', models.CharField(max_length=80)),
                ('publication_year', models.IntegerField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
